### ISSUE TITLE
UI based off of script - idea

### ISSUE THREAD

**Issue by BlueColorsin** [Stilic/FNF-LOVE#10]
While I was making a psych stage I noticed a setting called `"stageUI": ""` it used to be called pixel ui as a bool

This gave me an idea for this engine 
what we create a new folder in `assets/data/ui` then we add a new stage variable called `ui`
if it returns with nil then it gets set to default

For example you would be able to change
> Note Skins
> Default note positions
> Note Splashes   

by using self.bar = "" in the create

this is also where the ui is made too so basically everything can be edited 

Note: would be nice if it was a class and can be extended so you don't need to have the entire ui code every time but it would work with a script

**Comment by stilic** [comment]
maybe

**Comment by BlueColorsin** [comment]
> maybe

![AnyConv com__1062967054879170660](https://github.com/Stilic/FNF-LOVE/assets/76269429/c35bac7b-d372-4386-8df4-7079b1752eae)
