### ISSUE TITLE
Week 7 cutscene music continues during stage countdown

### ISSUE THREAD

**Issue by Gentronicus** [Stilic/FNF-LOVE#15]
In Week 7 of the original game, the music that plays during the intro cutscene stops when the countdown and transition to gameplay begins. 

Example:
https://github.com/Stilic/FNF-LOVE/assets/46545920/f00126ee-bb20-4e4e-912f-c6f557dd6fce

In Friday Night Funkin' LOVE as of now (commit 4bb1b08), the music continues during the countdown.

Example:
https://github.com/Stilic/FNF-LOVE/assets/46545920/e806ec57-b340-48a0-8633-bb081cdcf382

I was wondering whether this was an intentional feature or a bug.

**Comment by kiraluvyu** [comment]
Yes, this feature is intentional
as long as the cutscene music doesn't play when the song starts, that's okay👍

**Comment by Gentronicus** [comment]
It's pretty neat. I would suggest tweening the volume out or something for a more seamless transition, though, as the abrupt cut off could potentially make players assume it wasn't intentional.
