### ISSUE TITLE
Character Editor Crash

### ISSUE THREAD

**Issue by ChandelureF-5** [Stilic/FNF-LOVE#29]
So I tried going into the character editor, and... Well...
![Screenshot 2024-12-12 044457](https://github.com/user-attachments/assets/1e449a85-6c2b-4ea8-9f1b-d6a7eef49f28)
I don't know if I already reported this, but it's a pretty big problem for modders. ![:bro:](https://cdn.discordapp.com/emojis/1211905464413978714.webp?size=24)
So if that could be fixed at some point, it'd be well appreciated. Thank you for reading, and have a pleasant day!

**Comment by stilic** [comment]
There wasn't an update for editors in a while.
We have to fix them but for now, it means you can't access them.

**Comment by ChandelureF-5** [comment]
roger that
