### ISSUE TITLE
Tweening Library [Suggestion] 

### ISSUE THREAD

**Issue by BlueColorsin** [Stilic/FNF-LOVE#8]
### [**Tween.lua by Kikito**](https://github.com/kikito/tween.lua)   
![image](https://i.pinimg.com/1200x/bb/12/03/bb12038681429c0e313c3001a973ef0f.jpg)

**Comment by BlueColorsin** [comment]
okay so I got flux working lmao 

![love_dM8FYHjrOy](https://github.com/Stilic/FNF-LOVE/assets/76269429/8225f40e-e077-43d1-a7ee-2e654f453ed2)
```lua
flux = require "game/flux"

function stepHit()
    if curStep == 1 then
        flux.to(state.boyfriend, 2, {x = 20})
    end
end

function update(dt)
    flux.update(dt)
end
```

**Comment by stilic** [comment]
The Timer library already used in FNF-LÖVE has a tween module.

**Comment by stilic** [comment]
I don't think I will replace it with a new library unless it's really needed.
