### ISSUE TITLE
Pause Menu Music not ending on pause menu exit

### ISSUE THREAD

**Issue by BlueColorsin** [Stilic/FNF-LOVE#9]
Yeah the title really says it all but here is a video

https://github.com/Stilic/FNF-LOVE/assets/76269429/b23da116-51b9-4080-ae18-0a21e64ff498

**Comment by stilic** [comment]
> Yeah the title really says it all but here is a video
> 
>  Desktop.2023.09.09.-.01.13.14.11.mp4

The experimental branch is based off an older commit of the main branch.
No support will be provided for this branch because it will be manually merged into main later.

**Comment by BlueColorsin** [comment]
> > Yeah the title really says it all but here is a video
> > Desktop.2023.09.09.-.01.13.14.11.mp4
> 
> The experimental branch is based off an older commit of the main branch. No support will be provided for this branch because it will be manually merged into main later.

alright
I am still gonna use experimental until it is fully merged

also it was actually quite fun making a port with this, and learning how this engine worked was very neat
looking up to this engine and thank you for making it
